# Generated by Django 4.2.10 on 2024-02-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
