name: Testing 
on: push

jobs:
    test_portal:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: Run Django unit tests
        run:
          pip3 install -r requirements.txt
          python3 manage.py test